Repository replace-project/replace-backend, pull requests merged in 2023-07, with the labels that each got.

#3 feat : 리뷰 이미지 삽입, 삭제 기능 추가 ( #2 )
  re-place/src/main/java/com/replace/re/place/image/dao/ImageDao.java
  re-place/src/main/java/com/replace/re/place/image/dto/ImageDto.java
  re-place/src/main/java/com/replace/re/place/image/dto/ReviewImageDto.java
  re-place/src/main/java/com/replace/re/place/image/service/ImageService.java
  re-place/src/test/java/com/replace/re/place/image/service/ImageServiceTest.java
Labels: Feature

#4 feat:위도 경도 주소 등을 처리하는 기능( #2 )
  re-place/src/main/java/com/replace/re/place/store/dao/StoreDao.java
  re-place/src/main/resources/application.properties
Labels: enhancement

#6 feat: 리뷰 도메인 Dao 작성 ( #2 )
  re-place/src/main/java/com/replace/re/place/review/dao/ReviewDao.java
  re-place/src/main/java/com/replace/re/place/review/dto/ReviewDto.java
Labels: enhancement

#10 feat: 리뷰 작성 시 필요한 서비스단의 예외 구현 ( #2 )
  re-place/src/main/java/com/replace/re/place/category/dao/CategoryDao.java
  re-place/src/main/java/com/replace/re/place/category/service/CategoryService.java
  re-place/src/main/java/com/replace/re/place/global/ErrorCode.java
  re-place/src/main/java/com/replace/re/place/global/exception/category/CategoryNotCreatedException.java
  re-place/src/main/java/com/replace/re/place/global/exception/category/ReviewCategoryNotCreatedException.java
  re-place/src/main/java/com/replace/re/place/global/exception/image/ImageNotCreatedException.java
  re-place/src/main/java/com/replace/re/place/global/exception/image/ReviewImageNotCreatedException.java
  re-place/src/main/java/com/replace/re/place/global/exception/review/ReviewNotCreatedException.java
  re-place/src/main/java/com/replace/re/place/image/service/ImageService.java
  re-place/src/main/java/com/replace/re/place/review/service/ReviewService.java
Labels: enhancement

#13 refactor: 퍼사드 패턴을 적용한 서비스단 추가 ( #2 , #9 , #11 , #12 )
  re-place/src/main/java/com/replace/re/place/review/dto/PostReviewDto.java
  re-place/src/main/java/com/replace/re/place/review/service/FacadeReviewService.java
  re-place/src/main/java/com/replace/re/place/review/service/ReviewService.java
Labels: refactoring

#14 리뷰 삭제, 상세 조회 기능 구현
  re-place/src/main/java/com/replace/re/place/category/dao/CategoryDao.java
  re-place/src/main/java/com/replace/re/place/category/service/CategoryService.java
  re-place/src/main/java/com/replace/re/place/global/ErrorCode.java
  re-place/src/main/java/com/replace/re/place/global/exception/category/CategoryNotDeletedException.java
  re-place/src/main/java/com/replace/re/place/global/exception/category/CategoryNotFoundException.java
  re-place/src/main/java/com/replace/re/place/global/exception/category/ReviewCategoryNotDeletedException.java
  re-place/src/main/java/com/replace/re/place/global/exception/category/ReviewCategoryNotFoundException.java
  re-place/src/main/java/com/replace/re/place/global/exception/image/ImageNotDeletedException.java
  re-place/src/main/java/com/replace/re/place/global/exception/image/ImageNotFoundException.java
  re-place/src/main/java/com/replace/re/place/global/exception/image/ReviewImageNotDeletedException.java
  re-place/src/main/java/com/replace/re/place/global/exception/image/ReviewImageNotFoundException.java
  re-place/src/main/java/com/replace/re/place/global/exception/review/ReviewNotDeletedException.java
  re-place/src/main/java/com/replace/re/place/image/service/ImageService.java
  re-place/src/main/java/com/replace/re/place/review/dto/GetDetailedReviewDto.java
  re-place/src/main/java/com/replace/re/place/review/service/FacadeReviewService.java
  re-place/src/main/java/com/replace/re/place/review/service/ReviewService.java
Labels: enhancement
